services:
  benjamin-postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: benjamin
      POSTGRES_PASSWORD: benjamin
      POSTGRES_DATABASE: benjamin
    ports:
      - "6543:5432"

  keycloak-postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DATABASE: keycloak
      PGDATA: /data/postgres
    ports:
    - "6544:5432"
    volumes:
      - postgres:/data/postgres

  keycloak:
    image: bitnami/keycloak
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: keycloak-postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    ports:
      - "8082:8080"

  kafka:
    image: johnnypark/kafka-zookeeper:latest
    environment:
      ADVERTISED_HOST: 127.0.0.1
    ports:
      - "9092:9092"
      - "2181:2181"

volumes:
  postgres:
    driver: local