name: CI
on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: openjdk:17-alpine

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./gradlew clean build
      - name: Archive test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-logs
          path: build/test-results/test/TEST-*.xml